"""add_syllabus_courses

Revision ID: 3b8ab3f2cf72
Revises: 035a325e2d47
Create Date: 2026-05-28 21:38:53.112401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8ab3f2cf72'
down_revision: Union[str, None] = '035a325e2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
