"""add_data_analysis_sessions

Revision ID: 7b4ae9578a23
Revises: 9f0f91ffedda
Create Date: 2026-05-30 18:39:48.369420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b4ae9578a23'
down_revision: Union[str, None] = '9f0f91ffedda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
