"""add_scientific_articles

Revision ID: 9f0f91ffedda
Revises: 3b8ab3f2cf72
Create Date: 2026-05-30 04:26:59.868363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0f91ffedda'
down_revision: Union[str, None] = '3b8ab3f2cf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
